spring:
  application:
    name: feign-consumer
server:
  port: 5556
eureka:
  client:
    serviceUrl:
#      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true